name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          architecture: x64
      - name: Lint
        run: mvn spotless:check -f spotless.xml
      - name: Test
        run: mvn test jacoco:report
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.0
        with:
          paths: target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage
          update-comment: true
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2
        if: github.ref == 'refs/heads/main'
